spring:
  mvc:
    servlet:
      path: /api/v1
  data:
    redis:
      port: 6379
      host: localhost
      channel:
        follower: follower_channel
        achievement: achievement_channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: manticorestream7@gmail.com
    password: uoeg leun kfyb umjz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever

project-service:
    host: localhost
    port: 8082
    path: /api/v1
user-service:
    host: localhost
    port: 8080
    path: /api/v1
